version: 0.3
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://smartthermostatwiring.info"
 post_build:
   commands:
     - echo "post_build step"
